Default: &defaults
  user: docker
  password: docker
  host: db
  port: 5432
  database: docker
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: scaffold_test
  <<: *defaults

Staging:
  database: scaffold_staging
  poolsize: 100
  <<: *defaults

Production:
  database: scaffold_production
  poolsize: 100
  <<: *defaults
